spring.application.name=backend
server.port=8081

#Localstack S3 COnfig
application.s3.endpoint=http://localhost:4566
application.s3.region=us-east-1
application.s3.access-key=test
application.s3.secret-key=test